apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-mysql-service
  name:  test-mysql-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: my-mysql-app