---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name:  test-local-storage
#provisioner: kubernetes.io/no-provisioner
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - eu-west-1a
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name:  test-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName:  test-local-storage
  hostPath:
    path: "/data/test"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: test-local-storage
